server:
  port: 8084
spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: student-management
  datasource:
    thisIsTheDatasourceName:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost
    username: admin
    password: admin
    jpa:
      properties:
        hibernate:
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


